### PR TITLE
creates a demo folder inside each package

### PR DESCRIPTION
**Pull request by o-t-w**
Creates an index.html file that has the markup of a component as well as all the relevant CSS and JS, so that it can be easily rendered inside an iframe in a styleguide/pattern library.

### CODE REVIEW

**Comment by jpw** [comment]
@o-t-w thanks for looking at this, could you add some info to the PR as to what this is actually _for_ please? I think I can guess but would be good to hear your thoughts :)

**Comment by alexkilgour** [comment]
There is some good stuff here, but I think it needs some more discussion. It's possible that this might have a use outside of this repo, so could go as it's own  package in `frontend-toolkit-utilities` then used here. A few observations though:
- `util.promisify` is great, I had forgotten about this now we updated to Node 8. I wonder if it can be used elsewhere in this repo
- `munge` isn't a very descriptive name, look through the naming conventions of the rest of this file to see how other files are named
- have a look in the other files to see how errors are handled - we have an error handling script, and errors get passed up through the levels
- we shouldn't be creating the `demo` folder. This needs to exist already or none of it works (I will detail a bit later how I saw this working)
- both the `css` and the `js` should be inlined. We want a single `html` file at the end that is fully self-contained
- `js` should be compiled, not ES6
- the `css` and `js` should only be included in the `html` if they are needed

How I saw this working, is that when you create your component package you are required to include the following structure:
```
./demo
./demo/index.hbs
./demo/context.json
```
where a template exists at `view/index.hbs` we just include that template, where it doesn't we create our example handlebars html inside `./demo/index.hbs`. The `context.json` file is used to populate the template with data.

Within the demo folder we then have two optional files - `main.scss` and `main.js` - these are only included if we use `css` or `js` in our package respectively. The objective of `main.scss` is to incude the css from our package in the correct order, and for `main.js` it is to `init()` the module.

You can then use the code you have written to compile the `sass` and the `js`, then include the compiled code into a new `index.html` file that is created in `./demo/dist/index.html` (we create the dist folder on CI).

The outcome being that when we include a package via NPM in our design toolkit, we can render `./demo/dist/inde.html` inside an iframe to see a working example of the component package. We should also be able to create a watch task that compiles all of this on the fly as you are developing a package.

**Comment by alexkilgour** [comment]
Why have you made this `async`? this package is written using promises

**Comment by o-t-w** [comment]
I agree that I should have inlined the JS and CSS - I will work on that. 
Having a `context.json` is a great idea - I'll add that 👍 

Not sure I understand this comment:
> Why have you made this async? this package is written using promises

Surely async functions and promises are complementary? 

> now we updated to Node 8
Node 10 is now LTS. Can we not use it?

**Comment by alexkilgour** [comment]
> Why have you made this async? this package is written using promises
They are, but the rest of this large repo is written using promises. We shouldn't just be writing one single file using async/await. Could we rewrite the whole thing using async? yes. Is it worth it at this time? no.

> Node 10 is now LTS. Can we not use it?
Possibly, but we don't _need_ to make that change right now in here. If we are going to require Node 10, then it needs to be a decision taken across the whole components ecosystem

> Is it necessary for people to manually include that in the demo folder when it can be automated?
Yes, because it can't be automated, the reason being that you must have created the entrypoint `scss` and `js` files within the demo folder that assemble the sass @imports, and initialize the js module respectively. Also, there might not be a view template, so you should always include your own template in the demo folder, even if all it does is include the template from view.

Most importantly, having thought about this some more, I think this is more complicated than the use case covered here and needs a lot more thought. I also don't think it should live in this repository.

I would like to stop work on this until we can discuss it further. Don't get rid of this as there is a lot here that can be used, but I don't think we are in a position to carry on at the moment. Instead focus on finishing https://github.com/springernature/frontend-package-manager/pull/10

**Comment by jpw** [comment]
This work is good stuff thanks, and will be contribute towards a new package renderer standalone [utility](https://github.com/springernature/frontend-toolkit-utilities/) 🙂 

So leaving this open for now as a reminder.

**Comment by alexkilgour** [comment]
This is not needed any more due to the work being done by @jpw

**Pull request closed without merging**
